version: '3.7'

services:

    server:
        container_name: udemysgm_server
        build:
            dockerfile: Dockerfile
            context: ./server
        depends_on:
            - db
        ports:
            - 8080:8080
        restart: always
        env_file: .env
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - PORT=8080
            - MONGO_USERNAME=$MONGO_USERNAME
            - MONGO_PASSWORD=$MONGO_PASSWORD
            - MONGO_HOSTNAME=db
            - MONGO_PORT=$MONGO_PORT
            - MONGO_DB=$MONGO_DB
        command: ["npm", "run", "dev"]

    db:
        image: mongo:4.1.8-xenial
        container_name: udemysgm_db
        ports:
            - 27017:27017
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
        volumes:     
            - dbdata:/data/db

    mongoexpress:
        image: mongo-express:0.54.0
        container_name: udemysgm_mongoexpress
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_SERVER=db
            - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USERNAME
            - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD

volumes:
    dbdata:
    node_modules: